---
- hosts: all
  remote_user: root
  tasks:
  vars:
    f_reboot_now : false


  - name: Update
    apt: update_cache=yes
  - name: Upgrade
    apt: upgrade=dist
  - name: Check reboot
    register: file
    stat: path=/var/run/reboot-required get_md5=no

  - name: check_flag_reboot
    set_fact:
      f_reboot_now: true
    when: reboot_now is defined

  - debug:
    var=f_reboot_now

  - name: Send email for if reboot if neccesary
    local_action: mail subject='System {{ ansible_hostname }} needs rebooting after upgrade.'
    when: file.stat.exists == true and f_reboot_now == false

  - name: Reboot now
    command: /sbin/reboot
    when: file.stat.exists == true and f_reboot_now == true
